// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kejrhlmpsjwetbldvvrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlanJobG1wc2p3ZXRibGR2dnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTM1ODMsImV4cCI6MjA3MzkyOTU4M30.VsX4o3RC0k-xdjnZgc8liJ2pMV0AT9H2dPMkSC8qhbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});